[workspace]
resolver = "3"
members = [
    "crates/mft",
    "crates/qsv",
    "crates/timeline-explorer",
    "crates/waka",
]

[workspace.package]
version = "0.0.1"
authors = ["Dat Nguyen <dat.nguyen@bitbytelab.io>"]
edition = "2024"
readme = "README.md"
homepage = "https://github.com/nguyenthdat/forensics-tools"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = { version = "1.0" }
assert_cmd = "2.0"
bitflags = "2.9.1"
byteorder = "1"
chrono = { version = "0.4", default-features = false }
clap = { version = "4" }
criterion = "0.7.0"
csv = "1"
dialoguer = { version = "0.11.0" }
eframe = "0.32.0"
egui = "0.32.0"
encoding = "0.2"
env_logger = "0.11.8"
indoc = { version = "2.0" }
itertools = "0.14.0"
log = { version = "0.4.27" }
lru = "0.16.0"
mtf = { version = "0.6.1", default-features = false, path = "crates/mft" }
num-derive = "0.4.2"
num-traits = "0.2"
predicates = "3.1.3"
rand = "0.9.2"
rexpect = "0.6.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = { version = "0.12" }
skeptic = "0.13"
tantivy = { version = "0.24.2" }
tempfile = "3.2"
thiserror = "2.0.12"
winstructs = "0.3.0"
dirs = "6.0.0"
polars = { version = "0.50.0", features = ["full"] }
rayon = "1.10.0"
num_cpus = "1.17.0"
speedate = "0.17.0"
lexical-core = "1.0.5"
rustyline = { version = "17.0.0", features = [
    "buffer-redux",
    "derive",
    "regex",
    "rusqlite",
    "signal-hook",
    "with-fuzzy",
    "with-sqlite-history",
] }
rusqlite = "0.37.0"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "fmt",
    "std",
    "tracing-log",
] }
time = { version = "0.3.41", features = [
    "serde",
    "parsing",
    "macros",
    "large-dates",
    "local-offset",
    "serde-human-readable",
    "serde-well-known",
    "quickcheck",
    "formatting",
] }
bon = { version = "3.6.5" }
tantivy-query-grammar = "0.24.0"
nom = { version = "8.0.0" }
egui_extras = { version = "0.32.0", features = [
    "all_loaders",
    "chrono",
    "datepicker",
    "document-features",
    "serde",
    "svg_text",
    "syntect",
] }
rfd = { version = "0.15.4", features = [
    "tokio",
    "common-controls-v6",
    "file-handle-inner",
] }
encoding_rs = "0.8.35"
polars-sql = { version = "0.50.0", features = [
    "csv",
    "json",
    "serde",
    "parquet",
    "timezones",
    "binary_encoding",
    "dtype-decimal",
] }
