[workspace]
resolver = "3"
members = ["crates/mft", "crates/timeline-explorer"]

[workspace.package]
version = "0.0.1"
authors = ["Dat Nguyen <dat.nguyen@bitbytelab.io>"]
edition = "2024"
readme = "README.md"
homepage = "https://github.com/nguyenthdat/forensics-tools"
license = "MIT"

[workspace.dependencies]
anyhow = { version = "1.0" }
assert_cmd = "2.0"
bitflags = "2.9.1"
byteorder = "1"
chrono = { version = "0.4", default-features = false }
clap = { version = "4" }
criterion = "0.7.0"
csv = "1"
dialoguer = { version = "0.11.0" }
eframe = "0.32.0"
egui = "0.32.0"
encoding = "0.2"
env_logger = "0.11.8"
indoc = { version = "2.0" }
itertools = "0.14.0"
log = { version = "0.4.27" }
lru = "0.16.0"
mtf = { version = "0.6.1", default-features = false, path = "crates/mft" }
num-derive = "0.4.2"
num-traits = "0.2"
predicates = "3.1.3"
rand = "0.9.2"
rexpect = "0.6.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = { version = "0.12" }
skeptic = "0.13"
tantivy = { version = "0.24.2" }
tempfile = "3.2"
thiserror = "2.0.12"
winstructs = "0.3.0"
dirs = "6.0.0"
polars = { version = "0.50.0", features = ["full"] }
rayon = "1.10.0"
