[workspace]
resolver = "3"
members = ["crates/timeline-explorer", "crates/mft"]

[workspace.package]
edition = "2024"
homepage = "https://github.com/nguyenthdat/forensics-tools"
license = "MIT"
readme = "README.md"
version = "0.0.1"
authors = ["Dat Nguyen <dat.nguyen@bitbytelab.io>"]

[workspace.dependencies]
log = { version = "0.4.27" }
mtf = { path = "crates/mft", version = "0.6.1", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tantivy = { version = "0.24.2", features = ["json"] }
encoding = "0.2"
byteorder = "1"
bitflags = "2.9.1"
csv = "1"
thiserror = "2.0.12"
num-traits = "0.2"
num-derive = "0.4.2"
winstructs = "0.3.0"
lru = "0.16.0"
itertools = "0.14.0"
rand = "0.9.2"
clap = { version = "4" }
chrono = { version = "0.4", default-features = false }
anyhow = { version = "1.0" }
simplelog = { version = "0.12" }
dialoguer = { version = "0.11.0" }
indoc = { version = "2.0" }
rexpect = "0.6.2"
criterion = "0.7.0"
skeptic = "0.13"
assert_cmd = "2.0"
predicates = "3.1.3"
env_logger = "0.11.8"
tempfile = "3.2"
