[package]
name = "waka"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
eframe = { workspace = true, features = ["persistence", "serde", "wgpu"] }
epaint = { workspace = true, features = ["serde"] }
polars-sql = { workspace = true, features = [
    "csv",
    "json",
    "serde",
    "parquet",
    "timezones",
    "binary_encoding",
    "dtype-decimal",
] }
sqlparser = { workspace = true }
syntect = { workspace = true }
unicode-segmentation = { workspace = true }
qsv = { workspace = true, default-features = false, features = [
    "distrib_features",
    "polars",
] }
regex = "1.11.1"
