[package]
name = "waka"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
eframe = { workspace = true, features = ["persistence", "serde", "wgpu"] }
sqlparser = "0.58.0"
syntect = "5.2.0"
unicode-segmentation = "1.12.0"
